spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: Tak2268641!
#  application:
#    name: execution-service
#  jpa:
#    show-sql: true
#    generate-ddl: false
#    database: mysql
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
#        format_sql: true
#logging.level:
#  org.hibernate.SQL: debug
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
#server:
#  port: 0
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.value}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#
